server:
  port: 8086
spring:
  application:
    name: gmail_sender
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/gmail_sender
    username: root
    password: root
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create  # Options: none, validate, update, create, create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true  
  mail:
    host: smtp.gmail.com
    port: 587  #589
    username: otienogordon95@gmail.com
    password: bpgj adxp plhk dhbj
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8086 #${VERIFY_EMAIL_HOST}     
       
        
 #bpgj adxp plhk dhbj
 #gmail
  